### PR TITLE
[G5-49] Added readme-file for our github repo.

### PR DESCRIPTION
**Pull request by NorShiervani**

### CODE REVIEW

**Review by aohzork — APPROVED** [review]
looking good

**Comment by NorShiervani** [comment]
> You might refer a link to confluence for further documentation

I tried clicking on the link in incognito mode and it appears that you have to be authenticated to be able to view confluence documentation (it's not public).

**Review by AndreMorad — APPROVED** [review]

**Comment by aohzork** [comment]
> 
> 
> > You might refer a link to confluence for further documentation
> 
> I tried visiting the confluence docs in incognito mode and it appears that you have to be authenticated to be able to view confluence documentation (it's not public).

You can always type out the link to confluence, and then just add a text that "You need to be authorized"
Since this is a school project and Stephan is our teacher, he is authorized to our confluence group :)
And if this was a real project and a new teammember joined and was about to set up the environment, the new teammember would get authorized to be able to work:)

**Comment by NorShiervani** [comment]
> > > You might refer a link to confluence for further documentation
> > 
> > 
> > I tried visiting the confluence docs in incognito mode and it appears that you have to be authenticated to be able to view confluence documentation (it's not public).
> 
> You can always type out the link to confluence, and then just add a text that "You need to be authorized"
> Since this is a school project and Stephan is our teacher, he is authorized to our confluence group :)
> And if this was a real project and a new teammember joined and was about to set up the environment, the new teammember would get authorized to be able to work:)

I can quickly add the link to the readme tomorrow.

**Pull request merged**
